### ISSUE TITLE
test18 - partcules

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#10]
Le dernier test de ma base de test VISEO qui pose problème.
Il s'agit d'un système de particules.
Je te joins un scnx avec les images calculées par SE-RAY et SE-FAST à la date 0.2 s (dans SCNX/VISE).
Les deux fichiers log sont censés reproduire la même chose par le toolkit. C'était le cas avec les anciennes versions de CHORALE (au moins jusqu' à la 2016). Je jois les images obtenues avec le player fast.sps et ray.sps
Les problèmes:
- Avec SE-RAY, on a l'impression qu'il y a une particule proche du capteur (cf. plan objet et plan distance) en plus des paricules normales.
- Avec SE-FAST, messages d'erreur à l'exécution et image incorrecte.
Je joins également une nouvelle version du player qui corrige une erreur mineure.
[test18.zip](https://github.com/apajot/voc/files/1122648/test18.zip)

**Comment by apajot** [comment]
Je t'ai envoyé par mail le correctif pour le message d'erreur de SE-FAST. Les champs objets et distance sont ok, du coup je regarde ce que j'obtiens pour ray.
EDIT: en fait si on met le clipping du plan near à 0.01, on obtient la meme chose pour les plans objets et distance entre RAY et FAST (à un chtouille près), validant ton hypothèse d'objet très proche de la camera. Je vais regarder plus précisément ton log.

**Comment by apajot** [comment]
Corrigé, c'était une regression dans le positionnement des particules quand on fait un setLocalTransformation() entre le SimulationStart() et le GoUntil(0), uploadé (_2).

**Comment by abakleriche** [comment]
OK je clos
