### ISSUE TITLE
bi_leurre

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#11]
Il y a un souci lorsqu'on met dans la scène 2 instances d'un leurre SE-FLARE : lors du premier goUntil, le WB ne retrouve plus ses petits dans les variables des leurres.
Ci-joint un "scénario setk_player" en deux versions :
- 1leurre.log : une seule instance de leurre, ça marche bien (à condition de bien positionner le PYTHONPATH)
- 2leurres.log : erreurs sur les variables des leurres.
[bileurre.zip](https://github.com/apajot/voc/files/1249629/bileurre.zip)

Ci-joint également une version à jour du setk_player.
[setk_player.zip](https://github.com/apajot/voc/files/1249634/setk_player.zip)

**Comment by apajot** [comment]
Ok, je transfère à Lalaina.

**Comment by abakleriche** [comment]
Ca marche. Je clos.
