### ISSUE TITLE
Matériaux totalement transparents

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#13]
Petit souci sans gravité.
Lorsqu'on utilise des matériaux qui sont totalement transparents dans une bande (c'est typiquement le cas des jets en IR1) : 
- Avec SE-RAY
     Avec CHORALE 2016, les facettes correspondantes étaient bien éliminées :  elles n'apparaissaient ni dans le plan image ni dans le plan objet
    Avec la version courante : les facettes n'apparaissent pas dans le plan image, mais apparaissent dans le plan objet.
Il y a donc a priori une petite régression de SE-RAY
- Avec SE-FAST-IR : elles ne sont pas éliminées ; elles apparaissent dans le plan image (et dans le plan objet). Serait-il possible de les éliminer ?

Je ne te joins pas de données car le test utilise un objet que je préfère ne pas laisser traîner. Si tu en as besoin, j'en ferai un autre avec un objet plus simple.

**Comment by apajot** [comment]
Finalement j'ai les données nécessaires, je regarde si je reproduis.

**Comment by apajot** [comment]
Ton test est en rendu multibande ?
Pour SE-FAST, je reproduis le problème uniquement si j'ai un capteur en multibande. C'est normal dans ce cas, on ne peut avoir qu'une valeur d'alpha même si on rend sur plusieurs bandes. Du coup, si on rend sur les bandes A et B en même temps, si l'objet n'est pas complètement transparent sur la bande A et transparent sur la bande B, il laissera une trace sur la bande B car le même alpha > 0 sera utilisé pour les 2 bandes, et cet alpha atténuera le fond. L'alpha utilisé est une moyenne pondérée obtenue à partir des transmissions sur chaque bande (< 1 pour la bande A, 1 pour la bande B, donc alpha > 0, et donc atténuation).
Pour l'objectID, on l'écrit à partir du moment où l'alpha dépasse un certain seuil, d'où sa présence.

**Comment by abakleriche** [comment]
Oui, le problème n'apparaît qu'en multibandes, avec SE-RAY comme avec SE-FAST.

**Comment by apajot** [comment]
D'accord, ce n'est donc pas un problème mais une conséquence du multibande : on a qu'un seul plan objet pour toutes les bandes, l'objet apparait dans au moins une des bandes, il faut donc l'identifier....

**Comment by abakleriche** [comment]
OK, je clos.
Le tout est d'en être conscient.
