### ISSUE TITLE
Attribution du plan objet

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#17]
Il s'agit d'un problème dont on avait déjà parlé.
J'ai un objet d'ID = 200 et un leurre d'ID = 1. 
Chacun est dans un groupe de précision étendue.
Dans la version précédente du WB, la règle de l'attribution d'un pixel partagé à l'objet de plus faible ID ne s'appliquait pas car les deux objets sont dans des groupes distincts.
Maintenant que les objets sont traités ensembles, je m'attendais à ce que la règle s'applique dans tous les cas. Or, elle semble ne toujours pas être appliquée.
Ci-joint un log issu de VHEDAA avec les images intéressantes.
[planobj.zip](https://github.com/apajot/voc/files/1807558/planobj.zip)
Ce truc ennuie beaucoup Didier...

**Comment by apajot** [comment]
L'évolution qui a été faite ne consiste finalement pas à merger les groupes qui s'intersectent : ceci amènerait à des changements brutaux de résolution de rendu si on ne change pas la taille des FBOs à la volée, ce que l'on ne veut pas pour des raisons de performances. L'évolution consiste juste à considérer qu'un groupe sous-pixellique définit en fait un frustrum aussi petit que possible englobant les objets du groupe , et que tout ce qui se trouve dans la région 3D définie par ce frustrum est rendu  précisément. En gros, quand on fait le rendu de ce qui apparaitra sur l'imposteur, on rend toute la scène, en limitant le rendu à ce qui se trouve inclus dans le frustrum. Donc si deux groupes sous-pixelliques A et B sont alignés en Z, avec A devant B, mais que la géométrie de B n'est pas inclus dans le frustrum défini par A, le mélange utilisé sera "le plus devant d'abord". Ca c'est la théorie.
Pour vérifier que c'est bien cela qui se passe, il me faudrait un peu plus d'infos sur le scénario : l'objet d'id 200 est transparent sur les zones de recouvrement leurre/objet où le leurre a un impact ? Par rapport à la caméra, il a l'air devant le leurre (distance 2907 contre 2914) avec une bonne marge, donc ca semble aller dans le sens de ce que j'ai expliqué, et donc que ca marcherait comme je viens de te l'indiquer (ouf).

**Comment by abakleriche** [comment]
L'objet d'ID 200 est un simple cube parfaitement opaque et plus proche de la caméra que le leurre.  A l'origine le leurre est entièrement masqué. Lors du début de la séparation des deux objets, un ou plusieurs pixels sont partagés entre le cube et le leurre, et ces pixels sont attribués au cube (plus proche) et non au leurre (ID le plus faible).
Cela ne remet pas en cause le résultat de la simulation, car les deux objets sont quasi confondus lorsqu'une partie de l'énergie du leurre est attribuée à la cible. Par contre, le problème est que cet état de fait gêne Didier : l'augmentation et la diminution artificielle de la luminance de l'objet "cible" met en échec son algorithme de diagnostic automatique (raison du succès ou de l'échec du tir).

**Comment by apajot** [comment]
Comme si dans la réalité les photons arrivaient avec un identifiant d'objet....Ce qu'il se passe, c'est que le cube est certes opaque, mais l'imposteur ne l'est pas sur les bords du cube : le cube ne couvre que partiellement le pixel. Du coup on voit quand meme le leurre par transparence. Et donc il y a mélange avec le leurre qui est à l'arrière. Pourrais-tu lui demander si c'est complètement bloquant, ou regarder si l'évocation d'une évolution de son algorithme de son côté pour être un peu plus robuste lui cause des boutons ? Parce qu'on a bien une idée pour faire que ca marche, mais ca a un coût de rendu (ne pas restreindre les "sous-frustrum" au groupe sous-pixellique en Z)

**Comment by abakleriche** [comment]
Honnêtement je pense comme toi que la meilleure solution serait qu'il robustifie son algorithme.
Par contre son problème est qu'il n'a plus son sous-traitant préféré (groupement Capgemini - CESTA - ABAK du marché OS4) pour réaliser les travaux, et que le nouveau sous-traitant (Scalian Alyotech dans le marché Opesim) est certainement très loin d'avoir les compétences pour travailler dans VHEDAA, ce qui risque de le refroidir. A moins qu'il ne passe un avenant au marché VOC16 pour avoir de l'assistance sur VHEDAA, que nous pourrions assurer en tant que sous-traitant d'OKTAL SE (solution que je lui ai déjà suggérée mais dont j'ignore si elle a des chances de déboucher).
Didier m'a demandé de venir lundi matin terminer la formation que j'avais dû interrompre le 13 décembre en raison du décès de mon père. Nous  nous verrons sans doute à ce moment et je te propose d'en discuter avec Didier.

**Comment by abakleriche** [comment]
Problème résolu dans la livraison finale
