### ISSUE TITLE
Plantage SE-FLARE

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#18]
Semble se produire lorsque le leurre a fini sa vie avant la fin du scénario.
Plantage lors du seTkFinalise.
Ci-joint le log d'exécution. Le plantage avec le log est reproductible sous Windows
[plantage_se_flare.zip](https://github.com/apajot/voc/files/1879394/plantage_se_flare.zip)
Ci-joint également une version à jour du player
[setk_player.zip](https://github.com/apajot/voc/files/1879398/setk_player.zip)

**Comment by apajot** [comment]
Bonne nouvelle : je reproduis. Je cherche la deuxième bonne nouvelle maintenant....

**Comment by apajot** [comment]
Lalou a corrigé, je te fais un paquet cadeau. Dans tes cadeaux, tu veux quelles versions ? (le moins, le plus rapide)
