### ISSUE TITLE
Précision étendue

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#19]
Dans un scenario mettant en oeuvre un cube en défilement  face à un capteur, il arrive sur certaines images que l'énergie du cube chute d'un rapport 2, bien qu'il soit en précision étendue.
Ci-joint un log d'exécution
[test_precision_etendue.zip](https://github.com/apajot/voc/files/1915544/test_precision_etendue.zip)
La sous-image utilisée pour la précision étendue est de 128x128.
Lors de l'exécution du scénario, on constate par exemple que l'énergie du cube dans l'image 43 est deux fois inférieure à celle obtenue dans les images 42 ou 44.

**Comment by apajot** [comment]
Je regarde.
par contre, juste deux trucs au passage que je n'avais pas vu avant parce que je n'avais pas eu à bidouiller les logs...c'est certainement trop tard pour changer ca maintenant vu que tu as livré, mais bon, des fois que.
- si tu n'utilises pas le fichier SPS directement (ca a l'air d'etre le cas là, et en plus tu demandes la suppression du fichier SPS dans le seTkSignalFree), mets toi en render mode screen ou buffer, tu gagneras beaucoup.  Mais ce log là est peut-être pour du debug ?
- paramétrer la résolution de l'enhanced entity group à chaque frame ne sert à rien., et moi du coup je galère pour faire mes essais.....:)

**Comment by apajot** [comment]
C'est un problème d'aliasing de l'imposteur lui-même : quand j'active de l'anti-aliasing matériel je retombe sur une intensité quasi constante (32.6 pour la 42, 33.8 pour la  43)

**Comment by apajot** [comment]
Correctif uploadé, l'imposteur est traité de manière particulière pour garantir qu'il ne peut pas être aliasé. CentOS7_64 et RHE55_32 (j'ai lancé le tuto sur ma machine CentOS55, il a fonctionné jusqu'au bout). 

Au passage, j'ai changé le système pour le fichier de report de l'exe de trajectoire : il y en a toujours un de généré dans le dossier temporaire utilisé par python, avec un nom unique, mais je le supprime si la trajectoire a été générée correctement, et sinon j'affiche son chemin.

**Comment by abakleriche** [comment]
Pour être sûr de bien se comprendre, je t'explique d'abord ce que je fais.
Le scénario issu de VHEDAA met en oeuvre un cube mobile en face d'un capteur mobile. La distance entre le capteur et le cube varie de 3800 m à 3500 environ au cours du scénario qui dure un peu plus de 1 s.
Les images sont générées au pas de 0.005 s.
Je détermine l'éclairement de l'objet à partir d'une image en calculant l'intégrale L.dS où L est la luminance et S la surface attribuée à l'objet dans l'image (donc finalement la somme des luminances des pixels attribués à l'objet multipliée par la surface d'un pixel).
En théorie, cet éclairement devrait être quasi constant d'une image à l'autre, avec une légère augmentation au cours du scénario du fait du rapprochement. C'est globalement ce qui se passe.
J'ai rejoué le fichier log avec la nouvelle version du Workbench. Là ça marche plutôt pas mal : pendant le premier quart du scénario (environ), on a des variations entre 1.8e-6 et 2.4e-6, ce qui correspond à 2 pixels de fond. On peut en effet supposer que l'objet déborde très légèrement sur des pixels contenant essentiellement du fond (ce qui fait attribuer ces pixels à l'objet), mais que dans certains cas ce ne soit plus vrai, d'où la diminution.
J'ai rejoué le scénario VHEDAA avec le nouveau WB, et produit un nouveau log. Les images étant modifiées, et VHEDAA fonctionnant en boucle fermée, le scénario ne se déroule pas de manière rigoureusement identique (bien que très proche). Et là j'ai des choses plus étonnantes : entre l'image 002 et l'image 003, l'éclairement de l'objet passe de 2.36e-6 à 0.92e-6, soit une division par 2.5 environ. 9 pixels sont attribués à l'objet dans l'image 002, contre 4 seulement dans l'image 003.
Je te joins le nouveau log et quelques images.
[test_precision_etendue_new.zip](https://github.com/apajot/voc/files/1950590/test_precision_etendue_new.zip)
Autre chose bizarre : les images produites par VHEDAA et par le rejeu à partir du fichier log ne sont pas identiques. Les seules possibilités qui je vois pour expliquer cela seraient : 
- Les positions des entités sont stockées en ASCII dans le fichier log, alors qu'elles sont en binaire en mémoire dans VHEDAA, mais la différence doit être insignifiante.
- VHEDAA utilise le mode RenderToBuffer, alors qu'on se remet en mode RenderToFile quand on utilise le player. Tu penses que ça peut avoir un impact ?

**Comment by apajot** [comment]
Je regarde.
pour les différences entre VHEDAA et replay, quelles sont les différences que tu observes ? des positions différentes, ou des valeurs différentes de pixel mais les mêmes objets vus à travers les pixels ?

**Comment by apajot** [comment]
bon, pour la précision étendue j'ai trouvé, la conversion coords pixels -> coordonnées de vertex en espace caméra est en cause, mais je ne sais honnêtement pas pourquoi : l'imposteur généré ne couvrait pas toujours complètement la zone rendue en sous-pixellique en espace écran. Du coup j'ai simplement pris une marge, l'algo de résolution utilisé dans le shader me le permet sans introduire d'artefact.
je fais un patch.

**Comment by apajot** [comment]
le correctif est uploadé.

**Comment by abakleriche** [comment]
Cette version corrige le problème.
De plus, les différences entre les images issues de VHEDAA et du replay sont désormais quasi identiques (différence relative de  l'ordre de 10^-5 qui peut sans doute s'expliquer par le fait que les positions et attitudes des entités sont stockées en ASCII dans le fichier log).
