### ISSUE TITLE
Warning avec RENULIR

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#20]
Lors de l'utilisation d'un leurre RENULIR (objet créé dynamiquement au moyen des API setKGeometry et seTkMaterial), on observe un warning lorsque l'on place cet objet dans un groupe de préccision étendue:
 Warning: .Enhanced precision.Referenced entity: "rv6_Generique.leu0" is not a valid value!
 Warning: Setting the default value "".
rv6_Generique.leu0 est bien le nom sous lequel on a créé l'objet.
Ceci se produit avec SE-RAY comme avec SE-FAST.
Ci-joint en log SE-FAST pour setk_player
[warning_renulir.zip](https://github.com/apajot/voc/files/2140319/warning_renulir.zip)

**Comment by apajot** [comment]
Mon seTkPlayer ne doit pas être à jour, j'ai une commande non reconnue :  seTkOptronicSignalGetSignalObjectIdBuffer

**Comment by apajot** [comment]
bug trouvé, ca vient du fait que le nom de l'objet comporte un "." (marque de hiérarchie maintenant). On a fait un correctif avec Lalou, pour autoriser ca pour les noms d'entités dynamiques (telles que celles créées par le tkGeom). Pas sûr que ce soit très très pérenne. Sinon, le plus simple, qui marche sans relivraison, reste de remplacer les "." par des "_" ou tout autre caractère dans les noms d'entités.

**Comment by abakleriche** [comment]
OK, par sécurité j'adapte VISEO pour ne plus utiliser de '.' dans les noms d'objet.
