### ISSUE TITLE
test13 - disque  ajouté

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#5]
Il s'agit d'une anomalie que je rencontre (au moins avec SE-RAY, car je ne peux pas tester pour l'instant avec SE-FAST, à cause du plantage). Un disque lumineux est ajouté sur le leurre. cf. image obtenue avec VISEO.
Ce problème rappelle étrangement un bug qui a existé dans CHORALE en 2013 : le disque est l'image de la source éclairante. Or cette image ne doit pas être ajoutée si la source possède une géométrie (c'est le cas du leurre).
D'après mes essais, cette anomalie semble se manifester si on a défini un groupe de précision étendue, et que le leurre soit où non dans ce groupe.
J'ai essayé de reproduire le bug avec setk_player, mais, bizarrement, j'ai un plantage lors du rendu lors du rejeu (appel à seTkRenderSignal). Je te joins néanmoins le fichier log.
[test13_player_ray.zip](https://github.com/apajot/voc/files/1109020/test13_player_ray.zip)

**Comment by apajot** [comment]
Je regarde. Au passage j'ai réussi à utiliser le player sans problème, puisque je reproduis le crash....

**Comment by apajot** [comment]
Déjà il y a une erreur dans le player, Process_seTkGeomLightPointSetMaterial n'appelle pas la bonne fonction toolkit, donc ca fait n'importe quoi après...
même avec ca de corrigé, je n'arrive pas à aller au bout du calcul, ca crashe dans notre code (lié aux évolutions que Lalaina est en train de faire, le défaut de développer à pleins en même temps sur un projet...)

**Comment by apajot** [comment]
Pour le disque dans SE-RAY, cela vient du fait qu'il est demandé par l'application toolkit...l'emploi de seTkLIGHT_LIGHTING crée un feu et une lumière éclairante. Il faut mettre seTkLIGHTING pour ne pas avoir le feu.

Je regarde si ca marche dans SE-FAST.

**Comment by abakleriche** [comment]
Ah ? OK, comme ça, ça marche. Pourtant ça avait toujours marché avec seTkLIGHT_LIGHTING depuis l'origine des temps. Le code VISEO qui gère les leurres RENULIR dans SE-RAY est directement inspiré d'un code source fourni par OKTAL-SE à DGA MI (en 2007), qui utilisait seTkLIGHT_LIGHTING.

**Comment by abakleriche** [comment]
Avec la correction du player (un copié/merdé), il n'y a effectivement plus de plantage avec SE-RAY.
Le problème du disque étant résolu, je ferme l'issue.
