### ISSUE TITLE
Test14 - NaN

### ISSUE THREAD

**Issue by abakleriche** [apajot/voc#9]
Dans ce test une partie de l'hélico a des pixels dont la luminance est NaN sur l'image SE-FAST.
NB : ce problème disparaît lors qu'on désactive l'éclairement de l'astre en mode analyse.
Ci-joint le scénario
[test14.zip](https://github.com/apajot/voc/files/1121630/test14.zip)

**Comment by apajot** [comment]
Deux choses dans le correctif que je viens de mettre :
- les NaNs pour l'hélico (problème de robustesse numérique du calcul du lobe spéculaire)
- les problèmes menant aux violations d'assertion devraient être corrigés

Le dossier dans le zip est à mettre dans Software/Private/OGL_Shaders

**Comment by abakleriche** [comment]
OK ça marche. Je clos.
